# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

**1. NumPy Array**

To use external Library in PyThon, we will use the command called import.
In this example, we use external library called NumPy and give it a short name as np

In [2]:
#import เป็นคำสั่ง 
import numpy as np

In [ ]:
#สั่งชุดคำสั่งเพิ่ม 
!pip install numpy

In [ ]:
#check version
np.__version__

Vector or 1D Array

In [3]:
#arrayอยู่ในชุดคำสั่งของnp
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Matrix or 2D Array

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#เริ่มนับจาก 0
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[0]

1

In [6]:
a[2:5]

array([3, 4, 5])

In [7]:
L = [1,2,3,4,5,6,7,]
L[0]

1

In [8]:
L[2:5]

[3, 4, 5]

In [9]:
#เอาข้อมูลมาตั้งแต่ต้น
a[:6]

array([1, 2, 3, 4, 5, 6])

In [10]:
#เอาตั้งแต่ตำแหน่งที่ 3 จนสุด
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [11]:
a[-1]

10

In [12]:
a[2:-3]

array([3, 4, 5, 6, 7])

In [13]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [14]:
a[-5:-1]

array([6, 7, 8, 9])

In [15]:
#ช่วงกลับด้านเลยหาอะไรไม่เจอ
a[-2:2]

array([], dtype=int64)

In [16]:
np.size(a)

10

In [17]:
np.shape(a)

(10,)

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
#ก็จะเท่ากับ a[3] 
a[a[2]]

4

In [20]:
L[L[2]]

4

In [21]:
sorted(a, reverse=True)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [22]:
#แต่ array ไม่มี reverse
L.reverse()
L

[7, 6, 5, 4, 3, 2, 1]

In [23]:
a = a.reshape(1,10)
np.shape(a)

(1, 10)

In [24]:
#เมทริกซ์
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
L = [[1,2,3],[4,5,6],[7,8,9]]
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [26]:
#แถว 0 หลัก 0
a[0,0]

1

In [27]:
L[0][0]

1

In [28]:
#แถวที่ 1 เอาข้อมูลทั้งหมดมาโชว์
a[1,:]

array([4, 5, 6])

In [29]:
a[1]

array([4, 5, 6])

In [30]:
a[:,0]

array([1, 4, 7])

In [31]:
a[:,-1]

array([3, 6, 9])

In [32]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [33]:
a[1,:] = 0
a

array([[1, 2, 0],
       [0, 0, 0],
       [7, 8, 0]])

In [34]:
a[0:2,:] = 8 
a

array([[8, 8, 8],
       [8, 8, 8],
       [7, 8, 0]])

In [35]:
a.shape

(3, 3)

In [36]:
a.size

9

In [37]:
np.size(a,0)

3

In [38]:
#มันเป็นเมทริกมีแค่ กว้าง ยาว เลยมีแค่ 2 ถ้าเวกเตอร์จะมีแค่ 1 
#หาข้อมูลว่ามีกี่ dimension
np.ndim(a)

2

In [39]:
a.ndim

2

**Data is Matrix.**

* So, Matrix management == Data Management
* rows = samples
* columns = attributes, features

In [40]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [41]:
a = np.array(np_mix_matrix[:,1], dtype = int)
a

array([2, 4, 6])

**2. Special Type of Matrix**

In [42]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [43]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [44]:
c = np.ones((5,5))*8
c

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [45]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
c*d

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [47]:
#การคูณเมทริกซ์
np.matmul(c,d)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [48]:
a = np.ones((5,5))*9
a

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [49]:
np.sqrt(a)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [50]:
np.power(a,2)

array([[81., 81., 81., 81., 81.],
       [81., 81., 81., 81., 81.],
       [81., 81., 81., 81., 81.],
       [81., 81., 81., 81., 81.],
       [81., 81., 81., 81., 81.]])

In [51]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [52]:
#รูทของเมทริกซ์ 2*2 ค่าข้างในเท่ากับ 4
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [53]:
np.empty((10,10))

array([[4.68683787e-310, 0.00000000e+000, 2.97079411e-313,
        4.94065646e-324, 6.94122961e-310, 5.92878775e-323,
        6.94122983e-310, 3.18299369e-313, 2.97079411e-313,
        0.00000000e+000],
       [6.94122913e-310, 0.00000000e+000, 3.39519327e-313,
        4.94065646e-324, 6.94122961e-310, 4.68683767e-310,
        6.94122983e-310, 3.60739284e-313, 6.94104823e-310,
        0.00000000e+000],
       [6.94122913e-310, 0.00000000e+000, 3.81959242e-313,
        6.94104823e-310, 6.94122913e-310, 6.94122913e-310,
        6.94122983e-310, 4.03179200e-313, 6.94104823e-310,
        0.00000000e+000],
       [6.94122913e-310, 0.00000000e+000, 4.24399158e-313,
        6.94104823e-310, 6.94122913e-310, 6.94122913e-310,
        6.94122983e-310, 4.45619116e-313, 0.00000000e+000,
        0.00000000e+000],
       [1.50690022e-321, 0.00000000e+000, 4.66839074e-313,
        4.94065646e-324, 6.94122913e-310, 5.92878775e-323,
        6.94122983e-310, 4.88059032e-313, 0.00000000e+000,
        0.0

In [54]:
def addone(a):
    return a + 1

In [55]:
addone(3)

4

In [56]:
addone(a)

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

**3. Random**

In [57]:
#เลขที่สุ่มออกมาจะอยู่ในช่วง 0 - 1
rng = np.random.RandomState(0)
np.random.rand()

0.37429265522463173

In [58]:
#แบบใหม่สุ่มกี่รอบให้ออกมาเหมือนเดิม ต้องประกาศ rng ก่อน ถ้า rng.เลย ค่าที่ random มาค่าจะเปลี่ยนอยู่
rng = np.random.RandomState(0)
[ np.round(rng.rand()*10)for item in range(10)]

[5.0, 7.0, 6.0, 5.0, 4.0, 6.0, 4.0, 9.0, 10.0, 4.0]

In [59]:
[ np.round(np.random.rand()*10)for item in range(10)]

[8.0, 9.0, 9.0, 7.0, 9.0, 3.0, 4.0, 8.0, 3.0, 1.0]

In [60]:
#randomตั้งแต่ 0 - 4
rng = np.random.RandomState(0)
np.random.randint(5)

0

In [61]:
[np.random.randint(5) for item in range(10)]

[2, 0, 2, 2, 1, 1, 3, 4, 3, 0]

In [63]:
#แบบเก่าสุ่มกี่ครั้ง ค่าก็ออกเหมือนเดิม
np.random.seed(1)
np.random.randint(2,10)

7

In [64]:
np.round(np.random.rand(5,5))

array([[1., 1., 0., 1., 0.],
       [0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 1.],
       [1., 1., 0., 1., 1.]])

In [65]:
#เลขที่สุ่มมาจะซ้ำได้
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([ 2,  9,  9,  4, 10])

In [66]:
#เลขที่สุ่มมาจะไม่ซ้ำกัน
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

array([10,  3,  1,  5,  2])

In [67]:
rng = np.random.RandomState(0)
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

array([[0., 1., 1., 0., 1.],
       [1., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 1.],
       [1., 1., 0., 1., 1.]])

In [68]:
#จาก 1000 (0-1000) เลือกมา 100 แถว โดยไม่ให้ซ้ำเลย 
rng = np.random.RandomState(0)
idx_choose = rng.choice(1000,100, replace=False)
idx_choose

array([993, 859, 298, 553, 672, 971,  27, 231, 306, 706, 496, 558, 784,
       239, 578,  55, 906, 175,  14,  77,  31, 481, 310, 311, 883, 788,
        45, 103, 760,   1, 823, 710, 614, 790, 408, 736, 957, 366, 918,
       267, 230, 996, 635, 698, 251, 783, 819, 141, 316, 587, 331, 295,
       262, 432, 862, 582, 272, 270, 987, 319, 569, 643, 142, 202, 413,
       196, 264, 531, 252, 576, 738, 299, 740, 247, 926, 412, 389, 796,
       601, 654, 261, 456, 386, 982, 909, 693, 236, 501, 497, 874, 452,
       494, 923, 279, 638, 485, 568, 108, 367, 644])

In [69]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose.shape

(100, 5)

In [70]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[1., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 1., 0., 1.],
       [1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1.],
       [1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1.],
       [1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 0., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [0., 0., 1., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0.

**Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.**

In [73]:
p = np.random.rand(10,5)
p[:,-1] = np.round(p[:,-1])
p

array([[0.85162961, 0.15152488, 0.89003664, 0.65821289, 1.        ],
       [0.56407166, 0.939682  , 0.25184704, 0.78688428, 0.        ],
       [0.89090021, 0.27619869, 0.01524691, 0.064891  , 1.        ],
       [0.64115022, 0.73026872, 0.5043617 , 0.5575746 , 0.        ],
       [0.78263565, 0.75686525, 0.70000614, 0.96189241, 1.        ],
       [0.97792259, 0.59027645, 0.61925909, 0.63905322, 0.        ],
       [0.03302902, 0.78817638, 0.71018785, 0.07903169, 0.        ],
       [0.68634024, 0.53503738, 0.19121444, 0.05595335, 1.        ],
       [0.05361163, 0.21357531, 0.50266267, 0.09403111, 0.        ],
       [0.0201158 , 0.11946375, 0.94006251, 0.55886109, 1.        ]])

In [91]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 0, 2, 2, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 1, 0],
       [1, 2, 2, 1, 0]])

In [92]:
#ใช้ where เพื่อ random ค่าใน matrix ได้
row,column = np.where(np_matrix == 2) 
[(row[i],column[i]) for i in range(len(row))]

[(0, 0), (0, 2), (0, 3), (4, 1), (4, 2)]

**Ex 3. Why we cannot use this index ? Please fix it !!**
- numpy array

In [93]:
#idx = [1,2,3,4,5]
#np_matrix[idx,:]

#error เพราะ ขนาดมีแค่ 4 แต่ใน idx มี 5
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]

array([1, 2, 2, 1, 0])

In [77]:
#จะ random ไม่ให้ซ้ำ แต่ต้องสร้าง rng ก่อน 
rng = np.random.RandomState(22)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[1, 0, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [1, 2, 2, 0, 1],
       [0, 2, 1, 2, 1],
       [0, 0, 1, 0, 2]])

In [78]:
#ลบแถวที่ 0 - 1 แล้วก็ลบหลักที่ 1
np_matrix = np.delete(np_matrix,[1,2],1)
np_matrix

array([[1, 0, 0],
       [2, 0, 0],
       [1, 0, 1],
       [0, 2, 1],
       [0, 0, 2]])

In [79]:
#ตำแหน่งไหนเป็น 2 มันจะ true ให้
a = np_matrix == 2
a

array([[False, False, False],
       [ True, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False,  True]])

In [80]:
#เปลี่ยนจากที่เป็นเลข 2 ทั้งหมดให้เป็น 99 
np_matrix[a] = 99
np_matrix

array([[ 1,  0,  0],
       [99,  0,  0],
       [ 1,  0,  1],
       [ 0, 99,  1],
       [ 0,  0, 99]])

**Ex 4. Randomly create a data matrix of 10 samples with 5 features.**
* Then, randomly create a label vector for 10 samples. 
* Finally, seperate samples into 2 groups
* Group 1 called train_data (label == 0)
* Group 2 called test_data (label == 1)

In [81]:
data_matrix = np.random.randint(10, size = (10,5))
data_matrix

array([[0, 0, 8, 7, 1],
       [5, 4, 4, 4, 2],
       [7, 5, 2, 0, 6],
       [9, 6, 4, 2, 6],
       [1, 3, 9, 4, 3],
       [9, 9, 4, 6, 2],
       [2, 1, 2, 6, 5],
       [7, 0, 8, 7, 9],
       [9, 9, 1, 8, 7],
       [5, 0, 0, 6, 2]])

In [85]:
label_vector = np.random.randint(2, size = 10)
label_vector

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 0])

In [86]:
data_matrix[np.where(label_vector==0)]

array([[5, 4, 4, 4, 2],
       [7, 0, 8, 7, 9],
       [9, 9, 1, 8, 7],
       [5, 0, 0, 6, 2]])

In [87]:
data_matrix[np.where(label_vector==1)]

array([[0, 0, 8, 7, 1],
       [7, 5, 2, 0, 6],
       [9, 6, 4, 2, 6],
       [1, 3, 9, 4, 3],
       [9, 9, 4, 6, 2],
       [2, 1, 2, 6, 5]])